version: dev.{build}
skip_tags: true
image: Visual Studio 2019 Preview
configuration: Release
build_script:
- cmd: >-
    git submodule update --init --recursive

    msbuild EU4ToVic2.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    msbuild EU4toV2/EU4ToV2.vcxproj -property:Configuration=Release /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

    msbuild EU4ToVic2Tests/EU4ToVic2Tests.vcxproj /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
test: off
artifacts:
- path: Release
  name: EU4ToVic2-1.0M-prerelease
deploy:
- provider: GitHub
  release: windows_development_build
  description: The most recent build of the development version
  auth_token:
    secure: LBJzs4y9j0N5y0ajp7gmVk3Pvnec1UU5pTCdIMbQYUddEXQnWTJ79FXsd9SCs7YQ
  repository: paradoxGameConverters/EU4ToVic2
  artifact: EU4ToVic2
  prerelease: true
  force_update: true